CREATE TABLE admin_shipping_settings (
    settings_id VARCHAR(40) PRIMARY KEY,
    provider VARCHAR(40) NOT NULL DEFAULT 'superfrete',
    origin_cep VARCHAR(9) NOT NULL DEFAULT '',
    package_weight_kg NUMERIC(8,3) NOT NULL DEFAULT 0.300,
    package_height_cm INT NOT NULL DEFAULT 4,
    package_width_cm INT NOT NULL DEFAULT 25,
    package_length_cm INT NOT NULL DEFAULT 35,
    superfrete_base_url VARCHAR(160) NOT NULL DEFAULT 'https://sandbox.superfrete.com',
    superfrete_token TEXT,
    superfrete_services VARCHAR(80) NOT NULL DEFAULT '1,2,17',
    superfrete_user_agent VARCHAR(160) NOT NULL DEFAULT 'Baluarte/1.0 (contato@baluarte.com)',
    superfrete_cart_path VARCHAR(160) NOT NULL DEFAULT '/api/v0/cart',
    superfrete_checkout_path VARCHAR(160) NOT NULL DEFAULT '/api/v0/checkout',
    superfrete_label_link_path VARCHAR(160) NOT NULL DEFAULT '/api/v0/orders/{id}/tag/link',
    sender_name VARCHAR(120) NOT NULL DEFAULT '',
    sender_phone VARCHAR(40) NOT NULL DEFAULT '',
    sender_email VARCHAR(160) NOT NULL DEFAULT '',
    sender_document VARCHAR(30) NOT NULL DEFAULT '',
    sender_street VARCHAR(120) NOT NULL DEFAULT '',
    sender_number VARCHAR(20) NOT NULL DEFAULT '',
    sender_complement VARCHAR(120) NOT NULL DEFAULT '',
    sender_district VARCHAR(120) NOT NULL DEFAULT '',
    sender_city VARCHAR(120) NOT NULL DEFAULT '',
    sender_state VARCHAR(2) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
