FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S baluarte && adduser -S baluarte -G baluarte
COPY --from=builder /app/target/baluarte-core*.jar app.jar
USER baluarte
EXPOSE 8080
ENTRYPOINT ["java",
  "-XX:MaxRAMPercentage=75.0",
  "-jar", "app.jar"]
